### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by LavenderMoon** [DarkTwisterr/pushbullet#7]
Hi, what license is this under?

**Comment by DarkTwisterr** [comment]
Hi there,

It's released under  Simple Public License 2.0 (SimPL)

**Comment by LavenderMoon** [comment]
Could you add that to a `LICENSE.TXT` or `COPYING.TXT` file?

**Comment by DarkTwisterr** [comment]
Added a simple license file

**Comment by LavenderMoon** [comment]
Thanks.
